### ISSUE TITLE
Unable to enable plugin more-upload-stats-1.3.2

### ISSUE THREAD

**Issue by juup1ter** [Nachtalb/more-upload-stats#1]
```
03:17:09 Loading plugin handler
03:17:09 Enabled plugin Now Playing Search
03:17:09 Unable to enable plugin now_playing_sender
03:17:09 Rescanning normal shares...
03:17:09 Connecting to server.slsknet.org:2242
03:17:09 Listening on port 2234
03:17:10 Connected to server server.slsknet.org:2242, logging in...
03:17:10 3559 folders found before rescan, rebuilding...
03:17:10 1682 privileged users
03:17:10 [Warn] UPnP exception: UPnP does not work on this network
03:17:10 [Warn] Failed to automate the creation of UPnP Port Mapping rule.
03:17:11 You have no privileges left. They are not necessary, but allow your downloads to be queued ahead of non-privileged users.
03:17:13 3559 folders found after rescan
03:17:13 Finished rescanning public shares
03:17:23 Unable to enable plugin more-upload-stats-1.3.2
03:17:23 Could not enable plugin.
```

dragged and dropped to plugins folder and got this fail message @ 03:17:23 after i enabled it.

plugin was placed in both C:\Program Files\Nicotine+\pynicotine\plugins and C:\Users\k\AppData\Roaming\nicotine\plugins and got the same effect

**Comment by Nachtalb** [comment]
Ahh sorry, I only just now saw it. This is probably fixed with one of the newer versions. So I recommend you to get the latest version https://github.com/Nachtalb/more-upload-stats/releases.

Also, do not put the plugin in both folders at the same time. Just put it into whichever plugins folder opens when you click "Add Plugin" in the Settings screen.

**Comment by juup1ter** [comment]
hi! sorry for not clarifying further, i meant to say "plugin was tried in [these folders]"
after downloading the latest release, the output remains the same

```
10:08:38 Could not disable plugin.
10:08:39 Unable to enable plugin more-upload-stats-2.0.2
10:08:39 Could not enable plugin.
10:08:47 Unable to enable plugin more-upload-stats-2.0.2
```

i am on nicotine+ 3.0.6

**Comment by mathiascode** [comment]
> i am on nicotine+ 3.0.6

This plugin uses functionality that was introduced in Nicotine+ 3.1.x.

**Comment by juup1ter** [comment]
after upgrading:

```
11:43:37 Upload Statistics: Running version 2.0.2
11:43:37 Upload Statistics: Statistics file does not exist yet. Creating "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\build\stats.json"
11:43:37 Unable to enable plugin more-upload-stats-2.0.2
Traceback (most recent call last):
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 103, in load_stats
    self.stats.update(json.loads(path.read_text()))
  File "pathlib.py", line 1258, in read_text
  File "pathlib.py", line 1244, in open
  File "pathlib.py", line 1112, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\k\\AppData\\Roaming\\nicotine\\plugins\\more-upload-stats-2.0.2\\build\\stats.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pynicotine/pluginsystem.py", line 151, in enable_plugin
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 88, in init
    self.load_stats()
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 106, in load_stats
    self.save_stats()
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 111, in save_stats
    file.write_text(json.dumps(self.stats))
  File "pathlib.py", line 1277, in write_text
  File "pathlib.py", line 1244, in open
  File "pathlib.py", line 1112, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\k\\AppData\\Roaming\\nicotine\\plugins\\more-upload-stats-2.0.2\\build\\stats.json'
11:43:37 Could not enable plugin.
11:43:37 Upload Statistics: No new version available
11:43:56 Command /up is not recognized
11:43:58 Command /up is not recognized
11:44:01 Upload Statistics: Running version 2.0.2
11:44:01 Upload Statistics: Statistics file does not exist yet. Creating "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\build\stats.json"
11:44:01 Unable to enable plugin more-upload-stats-2.0.2
Traceback (most recent call last):
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 103, in load_stats
    self.stats.update(json.loads(path.read_text()))
  File "pathlib.py", line 1258, in read_text
  File "pathlib.py", line 1244, in open
  File "pathlib.py", line 1112, in _opener
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\k\\AppData\\Roaming\\nicotine\\plugins\\more-upload-stats-2.0.2\\build\\stats.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pynicotine/pluginsystem.py", line 151, in enable_plugin
  File "C:\Users\k\AppData\Roaming\nicotine\plugins\more-upload-stats-2.0.2\upload_stats\__init__.py", line 88, in init
    self.load_stats()
```

when creating the /build/ directory, and the empty file "stats.json", it continues to fail after a full restart:
```
11:46:28 Upload Statistics: No new version available
11:47:34 Command /up is not recognized
```

**Comment by Nachtalb** [comment]
> This plugin uses functionality that was introduced in Nicotine+ 3.1.x.

TBH I never checked for compatibility with older versions as I only just started using N+ a week ago :/ Sorry for that...

> after upgrading:

I thought I fixed that one already (╯°□°）╯︵ ┻━┻

**Comment by Nachtalb** [comment]
sooooo.... if it still doesn't work please shoot me: https://github.com/Nachtalb/more-upload-stats/releases/tag/v2.0.3

**Comment by Nachtalb** [comment]
Also please restart the client if possible after upgrading the plugin. I do some path injections and stuff cuz by default the environment N+ gives the plugins is a bit broken. The restart makes sure that everything is as pure as if Mr Clean came around. Usually this shouldn't be a problem but due to the plugin failing to lead / unload I am not quite sure.

**Comment by mathiascode** [comment]
> the environment N+ gives the plugins is a bit broken

Btw, feel free to report (reasonable) issues/improvements upstream. The plugin system can only be improved if people who actively depend on it report shortcomings. :)

**Comment by Nachtalb** [comment]
I wanted to already but I have to figure some stuff out atm. I'd like to run N+ for development inside my WSL2.0 machine but I am still on `21359` which means no WSLG and atm Windows10 Insider is done for so I can't upgrade to `21364+` and I can't upgrade to Win 11 either cuz I have a potato pc that isn't supported. 
Sooo... meh. Sad life. 

Don't want to work with Cygwin and all that shiz. Maybe I'll set up a complete Linux WM or find another way, idk yet.

**Comment by Nachtalb** [comment]
Hmm now that I think about it maybe my laptop is young enough. And afaik laptops often already have TPM 2.0 ￣へ￣ hmmmm

**Comment by juup1ter** [comment]
> sooooo.... if it still doesn't work please shoot me: https://github.com/Nachtalb/more-upload-stats/releases/tag/v2.0.3

works now, thanks!

**Comment by Nachtalb** [comment]
noice
