### ISSUE TITLE
Error thrown on loading the plugin

### ISSUE THREAD

**Issue by deafwired** [Nachtalb/more-upload-stats#5]
When i enable more-upload-stats it gives me the error in the image below, I don't remember getting this error until recently, I'm also unsure what the mysys64 part is and where it comes from.
![image](https://github.com/Nachtalb/more-upload-stats/assets/37221707/af0211f5-385b-4b82-ab83-5e184317652e)

**Comment by Nachtalb** [comment]
I haven't used nicotine+ in a while, I will try to look into it in a timley manner (by earliest start of next week)

**Comment by deafwired** [comment]
i recreated your project for a school assignment, but i think mine is slightly broken

**Comment by Nachtalb** [comment]
Seems like the plugin statistics have gone `bye bye 👋`. This error occurs if there is an empty stats  file. The plugin automatically creates backups for such cases. You find the backup path in the settings of the plugin. You can take the latest backup file and replace the `plugin/build/stats.json` with the backup file. And it should work again. 


ℹ️ Notice to me, better error handling and tell the user what's going on.

**Comment by Nachtalb** [comment]
I just uploaded the a new version of the plugin that has better error handling so this ticket is done and dusted		https://github.com/Nachtalb/more-upload-stats/releases/latest
