### ISSUE TITLE
Make the stats page look nice like in your screenshot

### ISSUE THREAD

**Issue by Rings4** [Nachtalb/more-upload-stats#7]
I'd love to be able to get the stats to appear as they do in your screenshot. Can you please add that functionality? It's just barebones for me.

![image](https://github.com/Nachtalb/more-upload-stats/assets/32050292/d1ea02cb-2bf8-4d52-ad1f-fad04a9eb76f)

**Comment by Nachtalb** [comment]
It seems the CSS (style configuration) is not loaded maybe there is a error logged in the console(?). 


I haven't used nicotine+ in a while, I will try to fix it timely (by earliest start of next week)

**Comment by Rings4** [comment]
> It seems the CSS (style configuration) is not loaded maybe there is a error logged in the console(?).
> 
> I haven't used nicotine+ in a while, I will try to fix it in a timely manner (by earliest start of next week)

There are no errors that I see. Just the usual
2024-07-02 19:59:01 Upload Statistics: Statistics generated and saved to "C:\Users\Master\AppData\Roaming\nicotine\plugins\upload_stats\build\index.html"

**Comment by Nachtalb** [comment]
when you're on the webpage with the statistics, can you press F12 or go via your browser options to open the Developer Console and see if there are any problems. (first article I found bout opening the dev tools: https://balsamiq.com/support/faqs/browserconsole/)

**Comment by Rings4** [comment]
> when you're on the webpage with the statistics, can you press F12 or go via your browser options to open the Developer Console and see if there are any problems. (first article I found bout opening the dev tools: https://balsamiq.com/support/faqs/browserconsole/)

![image](https://github.com/Nachtalb/more-upload-stats/assets/32050292/bfd09047-5aa6-4492-b80c-f5312ed7b8fe)

**Comment by Nachtalb** [comment]
It says it couldn't load some one of the JS files from disk. Maybe due to that something else failed as well. But it seems like you are using firefox - so I will try it with that one. But as said earilest starting next week. Thanks tho  for the input it aleady helped pinpointing the problem to some degree 👍

**Comment by Rings4** [comment]
> It says it couldn't load some one of the JS files from disk. Maybe due to that something else failed as well.
> 
> It seems like you are using firefox - so I will try it with that one. But as said earilest starting next week. Thanks tho for the input it aleady helped pinpointing the problem to some degree 👍

Awesome, looking forward to it, thanks again, and kudos for the plugin! It's a huge reason I switched from Soulseek to Nicotine+.

**Comment by actual-kwarter** [comment]
Can confirm I have the same issue on Firefox (v127.0.2) as well.

**Comment by Nachtalb** [comment]
I fixed the problem in the latest version https://github.com/Nachtalb/more-upload-stats/releases/tag/v2.2.1

**Comment by Nachtalb** [comment]
![image](https://github.com/user-attachments/assets/6d53b374-8728-43d3-be74-05a4b68e3f0a)

**Comment by Rings4** [comment]
Thanks a lot! It's working great now :D
