### ISSUE TITLE
AttributeError: 'Logger' object has no attribute '_add'

### ISSUE THREAD

**Issue by badprogramshere** [Nachtalb/more-upload-stats#9]
On Nicotine 3.2.9, enabling this plugin instantly results in this error, and none of the commands work. I'm not sure how to get a text log, so I took a screenshot of the error, as seen below.
![Screenshot 2024-07-28 at 9 22 49 PM](https://github.com/user-attachments/assets/bb030ae0-ec20-48de-a2a0-8975b398c9bb)

**Comment by Nachtalb** [comment]
I see, I have used a function that was intorduced in Nicotine+ 3.3.3 which I did not notice. I will see if I can workaround it.

**Comment by Nachtalb** [comment]
Try this one: https://github.com/Nachtalb/more-upload-stats/actions/runs/10133865122/artifacts/1748460405 and tell me if it works

**Comment by Nachtalb** [comment]
I published the a version with the appropriate bug fixes here: https://github.com/Nachtalb/more-upload-stats/releases/tag/v3.1.1

**Comment by Nachtalb** [comment]
I released a new version fixing that problem. Sorry for that blunder https://github.com/Nachtalb/more-upload-stats/releases/tag/v3.1.3

**Comment by badprogramshere** [comment]
> I released a new version fixing that problem. Sorry for that blunder https://github.com/Nachtalb/more-upload-stats/releases/tag/v3.1.3
> 
> Btw is there a reason why you don't upgrade to the latest Nicotine+ version 3.3.4? https://github.com/nicotine-plus/nicotine-plus/releases

Nicotine+ doesn't auto-update for me, at least on Mac, so I have to manually download and install each update. I can confirm it's fully working now, thanks :)
